vim.loader.enable()
require("user.sys")
require("plugin")
require("server")
vim.defer_fn(function()
    require("user.ui.core")
    require("user.mini")
    require("user.config.ide")
    require("user.ui.core.eqalizer")
end, 50)
